[version]
current = "v0.0.0-alpha"

[settings]
EtherScanApiKeys = ["AIIG5TBENEMJHXG8END5FXRM1N7ND3KPZI"]

rpcProviders = ["https://api-ethereum-mainnet.n.dwellir.com/b4942464-de9e-42fe-bfe4-80611faa04b" ]

ethArchives = ["https://api-ethereum-mainnet.n.dwellir.com/b4942464-de9e-42fe-bfe4-80611faa04b"]

[runtime]
LoggingUpperBound = 1000

[experiment]
trainingSetRatio = 0.7
